on:
  push:
    branches:
        - master
name: 🚀 Deploy Server
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        localDir: '.'
        remoteDir: ${{ secrets.PATH}}